version: "3.9"
services:
  dbpost:
    image: postgres:latest
    environment:
      POSTGRES_DB: Test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 486820
    volumes:
      - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
